id: template
namespace: io.kestra.terraform
tasks:
  - id: project-iam-extract
    description: Extract all iam at the project level
    type: io.kestra.plugin.core.log.Log
    message: "Running project IAM extract"

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    conditions:
      - type: io.kestra.plugin.core.condition.Expression
        expression: '{{ eq "prd" globals.env }}'
    cron: 0 4 * * 1
