#!/usr/bin/env python3
"""
Prepare generated Terraform provider docs for the Kestra website.

Run from the provider's generated docs directory (the one holding
resources/, data-sources/ and guides/ as nested <name>/index.md files).
Given the website's terraform docs directory as the single argument, it
rewrites each generated page's frontmatter:

  - Page already on the website: keep its hand-written frontmatter
    (SEO title / h1 / description) and refresh only the generated body.
  - New page: generate SEO frontmatter from the resource name by convention
    so new pages are never published with raw generated titles.

The body is always the freshly generated content.
"""
import os
import sys

# Words that must not be title-cased naively.
WORD_FIXES = {"api": "API", "kv": "KV", "id": "ID", "url": "URL",
              "sso": "SSO", "oidc": "OIDC", "sla": "SLA", "rbac": "RBAC"}


def humanize(name):
    return " ".join(WORD_FIXES.get(w, w.capitalize())
                    for w in name.replace("-", "_").split("_"))


def pluralize(phrase):
    words = phrase.split(" ")
    if words and not words[-1].endswith("s"):
        words[-1] += "s"
    return " ".join(words)


def split_frontmatter(text):
    """Return (frontmatter_without_fences, body)."""
    lines = text.split("\n")
    if lines and lines[0].strip() == "---":
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                return "\n".join(lines[1:i]), "\n".join(lines[i + 1:])
    return "", text


def generate_frontmatter(kind, name):
    noun = pluralize(humanize(name))
    lower = noun.lower()
    comment = "# generated by https://github.com/hashicorp/terraform-plugin-docs"
    if kind == "resources":
        return (f'title: "Terraform: Manage {noun} in Kestra"\n'
                f'h1: Manage Kestra {noun} with the Terraform Provider\n'
                f'{comment}\n'
                f'editLink: false\n'
                f'description: The kestra_{name} resource allows you to manage '
                f'{lower} in Kestra using Terraform.')
    if kind == "data-sources":
        return (f'title: "Terraform Provider in Kestra: Read {noun}"\n'
                f'h1: "kestra_{name} Data Source: Read {noun} via Terraform"\n'
                f'{comment}\n'
                f'editLink: false\n'
                f'description: The kestra_{name} data source allows you to read '
                f'{lower} in Kestra using Terraform.')
    title = humanize(name)
    return (f'title: "Terraform: {title}"\n'
            f'{comment}\n'
            f'editLink: false\n'
            f'description: {title} guide for the Kestra Terraform provider.')


def main():
    dest = sys.argv[1]
    for kind in ("resources", "data-sources", "guides"):
        if not os.path.isdir(kind):
            continue
        for name in sorted(os.listdir(kind)):
            gen = os.path.join(kind, name, "index.md")
            if not os.path.isfile(gen):
                continue
            with open(gen) as f:
                _, body = split_frontmatter(f.read())
            target = os.path.join(dest, kind, name, "index.md")
            if os.path.isfile(target):
                with open(target) as f:
                    fm, _ = split_frontmatter(f.read())
            else:
                fm = generate_frontmatter(kind, name)
                print(f"new page: generated frontmatter for {kind}/{name}")
            with open(gen, "w") as f:
                f.write(f"---\n{fm}\n---\n{body}")


if __name__ == "__main__":
    main()
