name: Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout provider
        uses: actions/checkout@v6
        with:
          path: terraform-provider-kestra

      - name: Checkout docs
        uses: kestra-io/actions/composite/checkout-and-auth@main
        with:
          gh-app-id: ${{ secrets.GH_BOT_APP_ID }}
          gh-app-private-key: ${{ secrets.GH_BOT_PRIVATE_KEY }}
          repository: kestra-io/docs
          path: docs
          ref: main

      - name: Transform docs for website
        run: |
          cd terraform-provider-kestra/docs/
          
          find  -type f -name "*.md" -exec sed -i 's/subcategory: ""/editLink: false/g' {} +
          find . -type f -name "*.md" -exec sed -i 's/```terraform/```hcl/g' {} +
          
          find data-sources -type f -name "*.md" -exec sed -Ei  's/page_title: "([^ ]+).*"/title: \1/g' {} +
          find resources -type f -name "*.md" -exec sed -Ei  's/page_title: "([^ ]+).*"/title: \1/g' {} +
          find guides -type f -name "*.md" -exec sed -Ei  's/page_title: "([^"]+)"/title: \1/g' {} +
          
          find . -type f -name "*.md" -exec sed -Ei  's/^-> (.*)/::alert{type="info"}\n\1\n::/g' {} +
          find . -type f -name "*.md" -exec sed -Ei  's/^~> (.*)/::alert{type="warning"}\n\1\n::/g' {} +
          find . -type f -name "*.md" -exec sed -Ei  's/^!> (.*)/::alert{type="danger"}\n\1\n::/g' {} +
          
          sed -Ei  's/page_title: "([^ ]+).*"/title: Provider configurations/g' index.md
          sed -Ei  's/^# kestra Provider/# Provider configurations/g' index.md
          mv index.md guides/configurations.md
          
          mkdir -p ../../docs/content/docs/13.terraform/
          cp -R * ../../docs/content/docs/13.terraform/

      - name: Push change to docs
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "feat(docs): update terraform docs"
          branch: main
          file_pattern: 'content/docs/13.terraform/*'
          repository: "docs"
          pull_before_commit: true

      - name: Slack - Notify CI failure
        if: failure()
        uses: kestra-io/actions/composite/slack-status@main
        with:
          channel: 'C09FE0QCN2E'
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          users-map: ${{ vars.GITHUB_TO_SLACK_MAP }}
          extra-text: 'Docs workflow failed.'
