name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: read

jobs:
  tests:
    name: tests
    uses: ./.github/workflows/test.yml
    secrets: inherit
  goreleaser:
    name: Release
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v7
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_ARMOR }}
          passphrase: ${{ secrets.SONATYPE_GPG_PASSWORD }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          args: release --clean

        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack notification
        if: success()
        uses: kestra-io/actions/composite/slack-status@main
        with:
          channel: 'C08KNSZGXQU'
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          users-map: ${{ vars.GITHUB_TO_SLACK_MAP }}
          suffix: ${{ github.ref_name }}

      - name: Slack - Notify release failure
        if: failure()
        uses: kestra-io/actions/composite/slack-status@main
        with:
          channel: 'C09FE0QCN2E'
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          users-map: ${{ vars.GITHUB_TO_SLACK_MAP }}
          suffix: ${{ github.ref_name }}
